#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h>

//#define DEBUG //enable serial printing

const char* ssid = "your network name";
const char* password = "your network password";
const char* auth = "this is generated by blynk app";
const unsigned char blynk_server_ip[4] = {192, 168, 2, 104}; /* blynk local server IP address */

const unsigned int seconds_to_micro = 1000000;
const unsigned int seconds_to_milli = 1000;
const unsigned int sleep_time_s = 10 * seconds_to_micro;

SimpleTimer timer;

void peripherals_config(void){
    pinMode(A0, INPUT);
}

void timerEvent(){
  unsigned int humidity_value = analogRead(A0);
  Blynk.virtualWrite(V0, humidity_value);
  
#ifdef DEBUG
  Serial.print("humidity_value");
  Serial.println(String(humidity_value));
#endif
}

void setup(void) {
  peripherals_config();

#ifdef DEBUG
  Serial.begin(115200);
  Serial.println();
#endif

//  Blynk.begin(auth, ssid, password); /* To be used with cloud server */
  Blynk.begin(auth, ssid, password, IPAddress(blynk_server_ip[0], blynk_server_ip[1], blynk_server_ip[2], blynk_server_ip[3])); 
  
  timer.setInterval(10*seconds_to_milli, timerEvent);  
  
 // ESP.deepSleep(sleep_time_s);
}
 
void loop(void) {
    Blynk.run();
    timer.run();
}
